name: Download YouTube Shorts

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL YouTube Shorts'
        required: true
        type: string

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup FFmpeg Kilat (~2-3 detik)
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Deno (~2 detik)
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Install yt-dlp Binary (~2 detik)
      - name: Install yt-dlp Binary
        run: |
          mkdir -p ~/.local/bin
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ~/.local/bin/yt-dlp
          chmod +x ~/.local/bin/yt-dlp
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Step baru: Mengambil cookie dari GitHub Secrets dan menulisnya ke file ./cookie.txt
      - name: Create Cookie File from Secret
        env:
          COOKIES_TEXT: ${{ secrets.COOKIES }}
        run: |
          echo "$COOKIES_TEXT" > ./cookie.txt

      - name: Download Shorts with yt-dlp
        run: |
          yt-dlp --cookies ./cookie.txt \
                 --remote-components ejs:github \
                 -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" \
                 --merge-output-format mp4 \
                 -o "downloads/%(title)s.%(ext)s" \
                 "${{ inputs.url }}"

      - name: Upload Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-shorts
          path: downloads/*.mp4
          retention-days: 7
